Repository techonerd/API_Bank, pull requests merged in 2021-10, with the labels that each got.

#1 initiate Django project
  Bank_api/__init__.py
  Bank_api/asgi.py
  Bank_api/settings.py
  Bank_api/urls.py
  Bank_api/wsgi.py
  manage.py
Labels: hacktoberfest

#4 README update for intital setup
  README.md
Labels: documentation

#5 Docs update
  README.md
Labels: documentation, enhancement
